#!/usr/bin/env bash

MODULE_NAME=json-schema-to-mongoose-schema
GLOBAL_NAME=jsonSchemaToMongooseSchema

rm -rf dist/*
esbuild src/index.ts --bundle --external:lodash --external:mongoose --platform=node \
  --outfile=dist/$MODULE_NAME.js --sourcemap --global-name=$GLOBAL_NAME \
  && tsc -d --emitDeclarationOnly --rootDir src --outDir dist \
  && mv dist/index.d.ts dist/$MODULE_NAME.d.ts \
  && refup dist/$MODULE_NAME.js $GLOBAL_NAME --no-default \
  || exit 1
